# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='wire.proto',
  package='',
  serialized_pb='\n\nwire.proto\"Y\n\x05Graph\x12\x1f\n\x05\x65\x64ges\x18\x01 \x03(\x0b\x32\x10.Graph.GraphEdge\x1a/\n\tGraphEdge\x12\x11\n\tfrom_node\x18\x01 \x02(\t\x12\x0f\n\x07to_node\x18\x02 \x02(\t')




_GRAPH_GRAPHEDGE = descriptor.Descriptor(
  name='GraphEdge',
  full_name='Graph.GraphEdge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='from_node', full_name='Graph.GraphEdge.from_node', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='to_node', full_name='Graph.GraphEdge.to_node', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=56,
  serialized_end=103,
)

_GRAPH = descriptor.Descriptor(
  name='Graph',
  full_name='Graph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='edges', full_name='Graph.edges', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_GRAPH_GRAPHEDGE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=14,
  serialized_end=103,
)

_GRAPH_GRAPHEDGE.containing_type = _GRAPH;
_GRAPH.fields_by_name['edges'].message_type = _GRAPH_GRAPHEDGE
DESCRIPTOR.message_types_by_name['Graph'] = _GRAPH

class Graph(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class GraphEdge(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _GRAPH_GRAPHEDGE
    
    # @@protoc_insertion_point(class_scope:Graph.GraphEdge)
  DESCRIPTOR = _GRAPH
  
  # @@protoc_insertion_point(class_scope:Graph)

# @@protoc_insertion_point(module_scope)
